version: '3'

services:

  # MongoDB service
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network_tp

  frontend:
    build:
      context: ./frontend
    container_name: frontend_tp
    volumes:
      - react_build:/app/dist
    environment:
      - NODE_ENV=production
    networks:
      - my_network_tp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_tp
    ports:
      - "4010:4010"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - mongo
    volumes:
      - static_volume:/staticfiles
      - /media:/media
    networks:
      - my_network_tp

  nginx:
    image: nginx:latest
    container_name: nginx_tp
    ports:
      - 8080:80
    volumes:
      - static_volume:/staticfiles
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/etc/nginx/html
      - /media:/media:ro
      - static_volume:/etc/nginx/html/static:ro
    depends_on:
      - frontend
      - backend
    networks:
      - my_network_tp

volumes:
  react_build:
  static_volume:
  mongo_data:

networks:
  my_network_tp: