import adminStyle from './admin.module.css'
import buttonStyle from './buttons.module.css'
import cartStyle from './cart.module.css'
import contactStyle from './contact.module.css'
import filterStyle from './filter.module.css'
import footerStyle from './footer.module.css'
import indexStyle from './index.module.css'
import marketplaceStyle from './marketplace.module.css'
import modalStyle from './modal.module.css'
import navbarStyle from './navbar.module.css'
import productCardStyle from './productcard.module.css'
import productDetailStyle from './product-detail.module.css'
import cartProductCardStyle from './cart-productcard.module.css'
import identifyStyle from './identify.module.css'

export {adminStyle, buttonStyle, cartStyle, cartProductCardStyle, contactStyle, identifyStyle, filterStyle, footerStyle, indexStyle, marketplaceStyle, modalStyle, navbarStyle, productCardStyle, productDetailStyle}